// Generates documentation from code, and fails when the two disagree.
//
// The payment lifecycle is described in exactly one place: the transition table.
// The state machine reads it, and this renders it. Without a check like this the
// document drifts, and a stale diagram describing a payment system is worse than
// no diagram, because people believe it.
//
// Run `npm run docs:generate` to write, `npm run docs:check` to verify.

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const shouldWrite = process.argv.includes('--write');
const OUTPUT_PATH = path.join('docs', 'state-machine.md');
const TABLE_MODULE = path.join(
  'apps',
  'api',
  'dist',
  'domain',
  'payment',
  'payment-transition-table.js',
);

const BACKTICK = String.fromCodePoint(96);
const EM_DASH = String.fromCodePoint(8212);
const RIGHT_QUOTE = String.fromCodePoint(8217);
const NEWLINE = String.fromCodePoint(10);

function code(value) {
  return `${BACKTICK}${value}${BACKTICK}`;
}

async function loadTable() {
  try {
    // pathToFileURL, because an absolute Windows path is not a valid ESM specifier.
    return await import(pathToFileURL(path.resolve(TABLE_MODULE)).href);
  } catch {
    console.error(
      `Could not load ${TABLE_MODULE}. Run "npm run build" first: the document is generated from compiled code, not parsed from source.`,
    );
    process.exit(1);
  }
}

const {
  PAYMENT_STATUSES,
  PAYMENT_TRANSITIONS,
  TERMINAL_PAYMENT_STATUSES,
  FUNDED_PAYMENT_STATUSES,
} = await loadTable();

const terminal = new Set(TERMINAL_PAYMENT_STATUSES);
const funded = new Set(FUNDED_PAYMENT_STATUSES);

function reachableFrom(status) {
  return [
    ...new Set(
      PAYMENT_TRANSITIONS.filter((transition) => transition.from === status).map(
        (transition) => transition.to,
      ),
    ),
  ];
}

function render() {
  const totalPairs = PAYMENT_STATUSES.length * (PAYMENT_STATUSES.length - 1);

  const statusRows = PAYMENT_STATUSES.map((status) => {
    const destinations = reachableFrom(status);
    const movesTo =
      destinations.length > 0 ? destinations.map((next) => code(next)).join(', ') : EM_DASH;
    const terminalLabel = terminal.has(status) ? 'yes' : 'no';
    const fundedLabel = funded.has(status) ? 'yes' : 'no';
    return `| ${code(status)} | ${terminalLabel} | ${fundedLabel} | ${movesTo} |`;
  });

  const transitionRows = PAYMENT_TRANSITIONS.map((transition, index) =>
    [
      `| ${index + 1}`,
      code(transition.from),
      code(transition.to),
      code(transition.trigger),
      code(transition.minimumEvidence),
      `${transition.description} |`,
    ].join(' | '),
  );

  const diagramRows = PAYMENT_TRANSITIONS.map(
    (transition) => `    ${transition.from} --> ${transition.to} : ${transition.trigger}`,
  );

  const tablePath = code('apps/api/src/domain/payment/payment-transition-table.ts');

  const lines = [
    '<!-- Generated by scripts/verify-docs.mjs. Do not edit by hand. -->',
    '',
    '# Payment lifecycle',
    '',
    `A payment holds one of ${PAYMENT_STATUSES.length} statuses, and exactly ${PAYMENT_TRANSITIONS.length} status-changing edges are declared in ${tablePath}. That table is the single source of truth: the state machine and this document are both derived from it, and CI fails if they disagree.`,
    '',
    `Of the ${totalPairs} ordered pairs of distinct statuses, only the edges below are permitted. The test suite enumerates the full Cartesian product of statuses and triggers rather than sampling it.`,
    '',
    '## Statuses',
    '',
    '| Status | Terminal | Funded | Can move to |',
    '| --- | --- | --- | --- |',
    ...statusRows,
    '',
    '## Transitions',
    '',
    '| # | From | To | Trigger | Minimum evidence | Why |',
    '| --- | --- | --- | --- | --- | --- |',
    ...transitionRows,
    '',
    '## Diagram',
    '',
    '```mermaid',
    'stateDiagram-v2',
    '    [*] --> pending',
    ...diagramRows,
    '```',
    '',
    '## Decisions worth knowing',
    '',
    `- **No edge leaves a terminal status.** A late event arriving against a finished payment is recorded and reported, never applied. Resurrecting a terminal payment is the bug class that double-credits a merchant.`,
    `- **${code('expired')} is deliberately not terminal.** A Pix code can be paid moments after it lapses. The money genuinely arrives, so ${code('expired -> paid')} exists; refusing it would be losing the customer${RIGHT_QUOTE}s payment.`,
    `- **Every transition into a funded status demands an authenticated provider read.** Appmax webhooks carry no signature of any kind, so a webhook may only schedule a read. It can never fund a payment by itself.`,
    `- **${code('unknown')} is a first-class status.** A provider call that did not produce a usable answer means it is unknown whether anything was created. The only route from ${code('unknown')} back to ${code('pending')} ${EM_DASH} the status in which another provider may be attempted ${EM_DASH} is ${code('RECONCILED_NOT_CREATED')}, which is proof that nothing exists to be paid twice.`,
    '',
  ];

  return lines.join(NEWLINE);
}

const generated = render();

if (shouldWrite) {
  await writeFile(OUTPUT_PATH, generated, 'utf8');
  console.log(`Wrote ${OUTPUT_PATH} (${PAYMENT_TRANSITIONS.length} transitions).`);
  process.exit(0);
}

let existing;
try {
  existing = await readFile(OUTPUT_PATH, 'utf8');
} catch {
  console.error(`${OUTPUT_PATH} does not exist. Run "npm run docs:generate".`);
  process.exit(1);
}

if (existing !== generated) {
  console.error(
    `${OUTPUT_PATH} is out of date with the transition table. Run "npm run docs:generate" and commit the result.`,
  );
  process.exit(1);
}

console.log(`${OUTPUT_PATH} matches the transition table.`);
